[package]
name = "openfaas_operato_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "time"] }
tracing = "0.1.37"
thiserror = { version = "1.0.43" }
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.100"
reqwest = "0.11.20"
