apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    annotation3: value3
    annotatison2: valuess298889
    openfaasfunctions.operato.rs/last-applied-spec: '{"service":"nodeinfo","image":"ghcr.io/openfaas/nodeinfo:latest","namespace":"openfaas-fn","envProcess":null,"envVars":{"envVar2":"value2","envVar":"value89","envVar2332":"vaaaaaaa"},"constraints":null,"secrets":["s3accesskey","s3accesskey","s2accesskey"],"labels":{"label":"value19","label2":"value","label3":"value3"},"annotations":{"annotatison2":"valuess298889","annotation3":"value3"},"limits":{"memory":"300Mi","cpu":"10m"},"requests":{"memory":"30Mi","cpu":"10m"},"readOnlyRootFilesystem":true,"secretsMountPath":null}'
  labels:
    faas_function: nodeinfo
  name: nodeinfo
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      faas_function: nodeinfo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        annotation3: value3
        annotatison2: valuess298889
      labels:
        faas_function: nodeinfo
        label: value19
        label2: value
        label3: value3
      name: nodeinfo
    spec:
      containers:
      - env:
        - name: envVar2
          value: value2
        - name: envVar
          value: value89
        - name: envVar2332
          value: vaaaaaaa
        image: ghcr.io/openfaas/nodeinfo:latest
        livenessProbe:
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
        name: nodeinfo
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
        resources:
          limits:
            cpu: 10m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 30Mi
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/openfaas/secrets
          name: nodeinfo-projected-secrets
          readOnly: true
      volumes:
      - emptyDir: {}
        name: tmp
      - name: nodeinfo-projected-secrets
        projected:
          sources:
          - secret:
              items:
              - key: s3accesskey
                path: s3accesskey
              name: s3accesskey
          - secret:
              items:
              - key: s2accesskey
                path: s2accesskey
              name: s2accesskey
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    annotation3: value3
    annotatison2: valuess298889
    openfaasfunctions.operato.rs/last-applied-spec: '{"service":"nodeinfo","image":"ghcr.io/openfaas/nodeinfo:latest","namespace":"openfaas-fn","envProcess":null,"envVars":{"envVar2":"value2","envVar":"value89","envVar2332":"vaaaaaaa"},"constraints":null,"secrets":["s3accesskey","s3accesskey","s2accesskey"],"labels":{"label":"value19","label2":"value","label3":"value3"},"annotations":{"annotatison2":"valuess298889","annotation3":"value3"},"limits":{"memory":"300Mi","cpu":"10m"},"requests":{"memory":"30Mi","cpu":"10m"},"readOnlyRootFilesystem":true,"secretsMountPath":null}'
  labels:
    faas_function: nodeinfo
  name: nodeinfo
  namespace: openfaas-fn
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    faas_function: nodeinfo
