apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-role
  namespace: openfaas-fn
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "create", "update", "get", "delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-rolebinding
  namespace: openfaas-fn
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: openfaas-fn
roleRef:
  kind: Role
  name: operator-role
  apiGroup: rbac.authorization.k8s.io
