apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-functions-operator
  namespace: openfaas-fn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-functions-operator-role
  namespace: openfaas-fn
rules:
- apiGroups:
  - operato.rs
  resources:
  - openfaasfunctions
  - openfaasfunctions/status
  - openfaasfunctions/finalizers
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-functions-operator-rolebinding
  namespace: openfaas-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfaas-functions-operator-role
subjects:
- kind: ServiceAccount
  name: openfaas-functions-operator
  namespace: openfaas-fn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-functions-operator
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-functions-operator
  template:
    metadata:
      labels:
        app: openfaas-functions-operator
    spec:
      containers:
      - args:
        - operator
        - controller
        - --functions-namespace
        - openfaas-fn
        - --update-strategy
        - one-way
        - run
        env:
        - name: RUST_LOG
          value: openfaas_functions_operato_rs=info,kube=off
        image: docker.io/jadkhaddad/openfaas_functions_operato_rs:0.2.0
        name: openfaas-functions-operator
      serviceAccountName: openfaas-functions-operator
