apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-functions-operator
  namespace: openfaas-fn
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openfaas-functions-operator-clusterrole
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: ["operato.rs"]
    resources: ["openfaasfunctions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-functions-operator-role
  namespace: openfaas-fn
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "create", "update", "get", "delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list", "get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-functions-operator-rolebinding
  namespace: openfaas-fn
subjects:
  - kind: ServiceAccount
    name: openfaas-functions-operator
    namespace: openfaas-fn
roleRef:
  kind: Role
  name: openfaas-functions-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openfaas-functions-operator-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: openfaas-functions-operator
    namespace: openfaas-fn
roleRef:
  kind: ClusterRole
  name: openfaas-functions-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-functions-operator
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-functions-operator
  template:
    metadata:
      labels:
        app: openfaas-functions-operator
    spec:
      serviceAccountName: openfaas-functions-operator
      containers:
        - name: openfaas-functions-operator
          image: docker.io/jadkhaddad/openfaas_operato_rs:latest
          args:
            - run
            - controller
