apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-functions-operator
  namespace: openfaas-fn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-functions-operator-role
  namespace: openfaas-fn
rules:
  - apiGroups: ["operato.rs"]
    resources:
      [
        "openfaasfunctions",
        "openfaasfunctions/status",
        "openfaasfunctions/finalizers",
      ]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-functions-operator-rolebinding
  namespace: openfaas-fn
subjects:
  - kind: ServiceAccount
    name: openfaas-functions-operator
    namespace: openfaas-fn
roleRef:
  kind: Role
  name: openfaas-functions-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfaas-functions-operator
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfaas-functions-operator
  template:
    metadata:
      labels:
        app: openfaas-functions-operator
    spec:
      serviceAccountName: openfaas-functions-operator
      containers:
        - name: openfaas-functions-operator
          image: docker.io/jadkhaddad/openfaas_operato_rs:latest
          args:
            - run
            - controller
          env:
            - name: RUST_LOG
              value: openfaas_functions_operato_rs=info,kube=off
